export const ERR_USER_NOT_FOUND = 'USER_NOT_FOUND'
export const ERR_INVALID_DATA = 'INVALID_DATA'
export const ERR_INVALID_TOKEN = 'INVALID_TOKEN'

export const ERR_DUPLICATE_EMAIL = 'DUPLICATE_EMAIL'

